version: 2

models:
  - name: stg_tutorial_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight.
    colums:
      - name: name
        tests:
          - not_null
          - unique
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values
