version: 2

models:
  - name: stg_tutorial_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight.
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight_lbs
        tests:
          - positive_values
      - name: weight_kg
        tests:
          - positive_values
