version: 2

models:

  - name: fct_page_views
    description: Page views fact table
    columns:
      - name: event_guid
        description: UUID of each unique event on the platform
        tests:
          - not_null
          - unique
      - name: session_guid
        description: UUID of each browsing session on the platform which can contain many events
      - name: user_guid
        description: UUID of the user that this event is associated with
      - name: page_url
        description: URL that the event happened on
      - name: created_at_utc
        description: Timestamp of the event (in UTC)
      - name: event_type
        description: Type of event
      - name: order_guid
        description: If the event is specific to an order (mostly used for checkout)
      - name: product_guid
        description: If the event is specific to a product