version: 2

models:

  - name: fct_page_views
    description: Page views fact table
    columns:
      - name: session_guid
        description: UUID of each browsing session on the platform which can contain many events
        tests:
          - not_null
      - name: user_guid
        description: UUID of the user that this event is associated with
      - name: first_name
        description: First name
      - name: last_name
        description: Last name
      - name: email
        description: User email
      - name: packaged_shipped
        description: Number of package shipped events
      - name: page_view
        description: Number of page view events
      - name: checkout
        description: Number of checkout events
      - name: add_to_cart
        description: Number of add to cart events
      - name: first_session_event
        description: Timestamp (in UTC) at which the first session occurs
      - name: last_session_event
        description: Timestamp (in UTC) at which the last session occurs
      - name: hours_diff
        description: Hours difference between the first and last sessions

  - name: fct_product_conversion
    description: Product conversion fact table
    columns:
      - name: product_name
        description: Product name
      - name: checkout_count
        description: Number of checkout events
      - name: page_view_count
        description: Number of page view events
      - name: conversion_rate
        description: Conversion rate of each product

  - name: product_funnel
    description: Product funnel
    columns:
      - name: nb_events
        description: Number of events including page_view, add_to_cart, and checkout
      - name: nb_page_view_events
        description: Number of page view events
      - name: nb_add_to_cart_events
        description: Number of add to cart events
      - name: nb_checkout_events
        description: Number of checkout events
      - name: page_view_rate
        description: Page view rate
      - name: add_to_cart_rate
        description: Add to cart rate
      - name: checkout_rate
        description: Checkout rate