greenery:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: gitpod
      password: gitpod
      port: 5432
      database: dbt
      schema: dbt_kan_o
      threads: 4
